### ISSUE TITLE
Problem compilation on 64bit Matlab R2019a on Windows 64bit

### ISSUE THREAD

**Issue by easterEodj** [ltfat/ltfat#104]
I followed the Windows install instructions to the letter, but received after successful compilation an error "Gateway function missing" for any of the mexfiles. I checked with verbose output the compilation process and everything seems fine.

I don't know what the issue is but it could be linked to 

Especially I used:
Windows 8.1 64bit
Matlab 64bit R2019a
fftw 3.3.5
tdm64bit gcc 5.1.0-2

Please let me know, if I can provide any more details.

My bet, I didn't download the R2018a precomiled builds. These work. However, if I want to compile myself the source code again same error.

**Comment by nholighaus** [comment]
I'm not the right person to answer this, but its recommended to use the precompiled build under Windows. I'm unsure how much support we can offer for Windows compilation issues.

**Comment by susnak** [comment]
Hi,
could you please post the verbose output?

**Comment by easterEodj** [comment]
After some delay, here are the verbose logs exectued on fresh compile of a clean version of the latest ltfat toolbox code. As mentioned any mexfile crashes as soon as it is executed.
[ltfat-master_verbose_compileLOG.txt](https://github.com/ltfat/ltfat/files/3293144/ltfat-master_verbose_compileLOG.txt)
[ltfat-master_verbose_testLOG.txt](https://github.com/ltfat/ltfat/files/3293145/ltfat-master_verbose_testLOG.txt)

**Comment by allthatsounds** [comment]
Hi easterEodj, in case you still want assistance, I think I know now what the issue could be, but I'd need to know which compiler you set up for mex. Do you want to continue discussions (otherwise, I'll close the issue within the next couple of weeks).

**Comment by allthatsounds** [comment]
fixed with ltfat 2.6.0
