### ISSUE TITLE
ifwt is broken on Mac

### ISSUE THREAD

**Issue by aressler38** [ltfat/ltfat#106]
I am using GNU Octave 4.4.1 on a Mac.

I tried to run the ifwt example from the documentation, but it doesn't work.

In the Octave command line, type `help ifwt`. There is a simple example.

>       A simple example showing perfect reconstruction:
>
>          f = gspi;
>          J = 8;
>          c = fwt(f,'db8',J);
>          fhat = ifwt(c,'db8',J,length(f));
>          % The following should give (almost) zero
>          norm(f-fhat)

Type that into the command line and get this error.
```
error: Unsupported data type..
error: called from
    comp_ifwt at line 74 column 10
    ifwt at line 153 column 6
```

I verified this works on a Windows 10 machine using the same Octave version. Something is broken on the Mac side of things for some reason.

I've also tried getting the `info` object from `fwt` and using that, but I get the same error.

**Comment by allthatsounds** [comment]
Thanks for letting us know!
Do you still require help with this?

**Comment by aressler38** [comment]
I don't. I ditched Mac OS several months ago.

**Comment by allthatsounds** [comment]
:D okay, so I will close this
