### ISSUE TITLE
MULTIDGTREALMP 

### ISSUE THREAD

**Issue by xxlhammer** [ltfat/ltfat#108]
There is no 'slow' version of the otrhogonal matching pursuit algorithms.

Therefore it does not work without the complied C-code.

Windows & Matlab: While LTFATMEX does not work on windows in a straightforward ways (see other issue), you can download the latest version including the binary files. This works.

Windows&Octave: The approach above does not work. So it seems MULTIDGTREALMP does not work with Octave.

**Comment by susnak** [comment]
> There is no 'slow' version of the otrhogonal matching pursuit algorithms.

No, but you can still use [franamp](http://ltfat.github.io/doc/frames/franamp.html) with any frame you like. It should even work with multiple frames at once trough the 'fusion' frame type. It is however *really* slow.

> Windows&Octave: The approach above does not work. So it seems MULTIDGTREALMP does not work with Octave.

In this case, you should try 
pkg install ltfat -forge
It is version 2.3.1, but should work.

**Comment by nholighaus** [comment]
I'm closing this as it seems solved. I do not think we intend to provide a non-compiled version of MULTIDGTREALMP.
