### ISSUE TITLE
What should I do to plot wavelets on Octave?

### ISSUE THREAD

**Issue by carlosdelfino** [ltfat/ltfat#112]
Please could someone help me with this question I posted on Math Stackexchange

https://math.stackexchange.com/questions/3509231/what-should-i-do-to-plot-wavelets-on-octave

**Comment by psoenderg** [comment]
Try wfiltinfo:

https://ltfat.github.io/doc/wavelets/wfiltinfo.html

**Comment by carlosdelfino** [comment]
Thanks, it helped a lot, I will study the function and related.

I'm taking notes at http://bit.ly/introwavelets
