### ISSUE TITLE
rms is a Matlab function with a different call signature

### ISSUE THREAD

**Issue by egaudrain** [ltfat/ltfat#113]
The call signature of the [rms](https://github.com/ltfat/ltfat/blob/master/sigproc/rms.m) function in LTFAT is different from the one in Matlab's Signal Processing Toolbox. For instance calling `rms(x,2)` performs RMS calculation along the second dimension for the Signal toolbox, but crashes with LTFAT.

Wouldn't it be relatively easy to make the LTFAT version of the function compatible with the Matlab Signal Proc. toolbox call? Would solve some headaches.

I'd propose something, but I'm not too familiar with the LTFAT argument handling system.

Cheers!

**Comment by susnak** [comment]
Hi,
could you please check with the latest commit?
Thanks!

**Comment by egaudrain** [comment]
Awesome! Works for me :)
