### ISSUE TITLE
Unable to run demo_blockproc_basicloop

### ISSUE THREAD

**Issue by johnbodhi** [ltfat/ltfat#114]
I am trying to simply run demo_blockproc_basicloop('playrec') to process some streaming audio input, but I keep getting the error:

>> demo_blockproc_basicloop('playrec')
Unrecognized function or variable 'demo_blockproc_header'.

Error in demo_blockproc_basicloop (line 29)
if demo_blockproc_header(mfilename,nargin)

I can't even run demo_blokproc_basicloop without an argument without getting the error:

>> demo_blockproc_basicloop
Unrecognized function or variable 'demo_blockproc_header'.

Error in demo_blockproc_basicloop (line 29)
if demo_blockproc_header(mfilename,nargin)

This is unusual because it was working perfectly for sometime, and then just stopped working.

Any ideas?

**Comment by susnak** [comment]
Hi, 
the file
demo_blockproc_header.m
should be in the comp subdirectory and the director must be in your path after ltfatstart / pkg load ltfat
is run.
