### ISSUE TITLE
Unable to edit demo_blockproc_slidingsgram java files

### ISSUE THREAD

**Issue by blancaster7** [ltfat/ltfat#117]
I wanted to edit the demo_blockproc_slidingsgram java files so I could add a pause button to the GUI. However, when I edit the java files and recompile them nothing changes to the demo. Do you have any suggestions for how to edit this demo? Also, I'm using octave.

**Comment by susnak** [comment]
Hi. Sorry for the late reply. It is a bit tricky. You need to rewrite the jar file and restart Octave.
