### ISSUE TITLE
C code of chirpzt

### ISSUE THREAD

**Issue by PAk-CatchFire** [ltfat/ltfat#124]
Hello.
I am an engineering student and I find this library amazing for octave.
Right now I am using czt, and I have read the functions comes with the c equivalent, but I am not able to find it in the source code file.

Where could I find the source code of the C implementation of the ltfat chirpct function?

Thank you

**Comment by susnak** [comment]
Hi, the C implementation is in libltfat/src/goertzel.c

**Comment by PAk-CatchFire** [comment]
Thank you Susnak.

So actually what it is using the library is Goertzel, right?
I was seeing that the Octave script was not able to separate two tones at close frequency (400Hz and 405Hz) unless I increased the FFT size from 2^10 to 2^11, without changing the ChirpZ part.

![goertzel_1](https://user-images.githubusercontent.com/4245130/102000930-b580d600-3cec-11eb-9bbd-f72d00316658.JPG)
![goertzel_2](https://user-images.githubusercontent.com/4245130/102000935-b9145d00-3cec-11eb-8dec-d3dd35a3da7c.JPG)

**Comment by PAk-CatchFire** [comment]
About the goertzel.c file, I have some doubts about how to extract the function from it:

- Where is  LTFAT_NAME defined?

- Where is LTFAT_API defined?

- Is it possible to take the function to make it work in another piece of code without dependencies? I would like to port it to an arduino board.

Regards

**Comment by susnak** [comment]
There is a matlab implementation: ltfat/comp/comp_chirpzt.m and a C implementation interfaced trough ltfat/oct/comp_chirpzt.cc. 
Please see http://ltfat.github.io/libltfat/ for what the macros mean. 
For chirpzt, you will need a FFT implementation (libltfat uses FFTW or kissFFT), while Goertzel alg. does not need any.

**Comment by PAk-CatchFire** [comment]
Thank you Susnak.
I am trying to extract both the Chiprzt and Goertzel functions to compare them using arduino for audio analysis (multiple tones vs single tones). I have my own fft function, so that is not an issue.
I am trying to keep the clean calls used in octave script:
```
% DTFT samples. The frequency range of interest is 803.9-853.5 Hz
ckchzt = chirpzt(f,K,fdiff,foff,fs);
```
However, I am  having issues understanding all the interface in ltfat. 
Sorry to bother you, but could you give me a hand on this? Just the function in plain C would be enough.

Best Regards

**Comment by susnak** [comment]
Which data type is your input? Real or complex? double. float? Does your compiler support C99 complex numbers? I can also make it C++11 compatible (std::complex).

**Comment by PAk-CatchFire** [comment]
Hi susnak, I am using C (not C++) on the MCU.
I use floating point (since double is very computing costly). I do use complex tipe defined as:

```
typedef struct cplex {
   float re;
   float im;
} COMPLEX;
```
For the moment, this weekend I have ported the zoom fft czt function included in this file:
[https://github.com/omnister/fftp/blob/master/fftlib.c](url)
It is working reasonable well (I do see some drift sometimes, with ideal tones, but maybe is the signal generation).

Thank you

**Comment by susnak** [comment]
Can you check if the compiler supports C99 complex type? https://en.cppreference.com/w/c/numeric/complex

**Comment by PAk-CatchFire** [comment]
Hello susnak.
Yes it does  support C99 complex type.  Please mind, it is more than enough to use float type instead of double type, because of performance on the MCU.

**Comment by susnak** [comment]
Hi, here is a simplified version. The FFT calls are commented out with // FIXME:. You will have to replace them with your own. Please make sure you link it with C99 libm with complex numbers support and overloaded exp working with complex numbers. I have only checked that it compiles.
[Goertzel.zip](https://github.com/ltfat/ltfat/files/5730688/Goertzel.zip)

**Comment by susnak** [comment]
gga(
const float* fPtr /* W input arrays (length LxW) */, 
const float* indVecPtr /* Array of normalized frequencies (length MxW) */, 
int L, 
int W, 
int M,
 float complex* cPtr /* Output array MxW */
)

**Comment by susnak** [comment]
chzt(
const float* fPtr,  /* W input arrays (length LxW) /,
int L, int W,
int K, /* Number of chzt samples */
const float deltao, /* Step in normalized frequency */
const float o, /* Starting normlized frequency */
float complex* cPtr /* Output array KxW */
)

**Comment by PAk-CatchFire** [comment]
Thank you Susnak.
I will try this code ASAP on the embedded board. 

I wish you a happy 2021!!
