### ISSUE TITLE
Is there some functions to design of oversampled NPR or PR  uniform dft Filterbank?

### ISSUE THREAD

**Issue by zuowanbushiwo** [ltfat/ltfat#125]
Hi   
       I am studying echo cancellation based on subband adaptive filtering recently. I need to find a way to design FIR prototype filter for analysis and synthesis filter bank. I have read many papers and still don’t know how to implement it.  Is there  any reference in this project about this？
      thanks!

**Comment by KKevinLee** [comment]
hi, zuowanbushiwo,
i also need a help from you, can i add a friend to you?

**Comment by zuowanbushiwo** [comment]
@KKevinLee  
   What do you mean?

**Comment by allthatsounds** [comment]
Hi zuowanbushiwo,
I believe LTFAT's filterbank functions do what you are looking for: https://ltfat.github.io/notes/ltfatnote028.pdf
Maybe just have a look and let me know if you need a hand

**Comment by nholighaus** [comment]
Hi everyone,to my knowledge, LTFAT has no method specifically for designing a filter according to some desired criteria. Instead, it offers a sizable selection of filter prototypes that can be selected. Maybe one of them fulfills your criteria. Have a look at 'firfilter' or 'firwin', respectively, as allthatsounds indicated.Am 21.12.2020 11:03 schrieb allthatsounds <notifications@github.com>:
Hi zuowanbushiwo,
I believe LTFAT's filterbank functions do what you are looking for: https://ltfat.github.io/notes/ltfatnote028.pdf
Maybe just have a look and let me know if you need a hand

**Comment by KKevinLee** [comment]
Hi, my email address is KKevinLee@ProtonMail.com.
Please contact me @zuowanbushiwo 
Thanks.

**Comment by zuowanbushiwo** [comment]
@allthatsounds 
  Thank you so much for your help,  I still haven't found a function that can design analysis and synthesis prototype filter. From the articles I read, I understand that it is necessary to set the stopband gain, subband aliasing, and transmission distortion parameters.

**Comment by zuowanbushiwo** [comment]
@nholighaus 
   thanks，I think you might be right。

**Comment by susnak** [comment]
@zuowanbushiwo 
I am afraid there is no silver bullet for you in LTFAT. If you could describe your problem a bit more, then we might be able to suggest something. The solution can range from very easy (if you are talking about an uniform filterbanks obtained by modulating as single prototype filter), to hard or impossible if you have completely general FIR filterbank and you are looking for a PR counterpart.
