### ISSUE TITLE
Install cant find fftw3 libs

### ISSUE THREAD

**Issue by lonce** [ltfat/ltfat#128]
Ubuntu 18.04
Octave 5.2.0
FFTW 3.x 

Hi - 
   I can't seem to get the ltfat install to see my fftw3 libraries.
I compiled and installed fftw3 with threads enabled, and all the fftw3 libraries look properly installed  in:
/usr/lib/x86_64-linux-gnu
and my library path is set accordingly: 
echo $LD_LIBRARY_PATH
/usr/lib:/usr/lib/x86_64-linux-gnu

and yet, the ltfat install has repeated failures:
/snap/octave/30/usr/bin/ld: cannot find -lfftw3_threads
/snap/octave/30/usr/bin/ld: cannot find -lfftw3
/snap/octave/30/usr/bin/ld: cannot find -lfftw3f_threads
/snap/octave/30/usr/bin/ld: cannot find -lfftw3f

Any ideas of what I can do to get this to make? 

Thanks,
                          - lonce

**Comment by susnak** [comment]
Dear Lonce,

the compilation queries mkoctfile for the location of the libraries. Could you run this from the regular terminal (not from within Octave)?

mkoctfile -p LFLAGS
mkoctfile -p FFTW_LIBS

Maybe the snap Octave package does something differently.

Zdenek

**Comment by lonce** [comment]
Hi Zdenek,

     Thanks for the help. Indeed,
mkcotfile -p LFLAGS
only shows
-L/snap/octave/30/lib

But I can't even put a softlink to my in /snap/octave/30/lib to the 
/usr/lib/x86_64-linux-gnu fftw3 livs because /snap is all read-only.
I suppose that means I have to build and install octave from source.

Thanks again,
                         - lonce
