### ISSUE TITLE
Release 2.5.0

### ISSUE THREAD

**Issue by allthatsounds** [ltfat/ltfat#138]
Dear all,
finally, there is a pre-release of 2.5.0 at https://github.com/ltfat/ltfat/releases/tag/v2.5.0
I would appreciate reports from your installation attempt. I shamelessly copied the steps I'd ask you to follow from
Zdeneks previous releases below.

Thanks,
Clara

Please report your results as a reply to this ticket. Please also include your OS and whether you are using Matlab or GNU Octave.

Matlab users:
-----------------

1) Get the appropriate release package from https://github.com/ltfat/ltfat/releases/tag/v2.5.0

2)  Make sure that your regular LTFAT installation is not in the search path and run the following:
```
ltfatstart
ltfatmex % (not on Windows)
ltfatmex playrec % (not on Windows)
test_all_ltfat % This might take a long time
```
3) Also run 
```
demo_blockproc_slidingsgram(gspi); 
```
4) And this too
```
mulaclab(gspi,44100);
```
This should open GUI and is should be possible to select some area using the mouse (right click finishes the selection). Then click the Apply button and a second plot should appear with the selected area removed.

**Comment by germknoedlspeck** [comment]
Hi!

OS: Windows 10 Pro, Version 21H2, OS build 19044.1706
Matlab R2021b

After a few minutes when starting start_all_ltfat, I get the following error message (including the last header in the cmd window before the error message):

 =================== TEST_CONSTRUCTPHASE ====================== 
Unrecognized function or variable 'comp_heapint'.

Error in constructphase (line 158)
    newphase=comp_heapint(abss,tgrad,fgrad,a,tol(1),flags.do_timeinv);

Error in test_constructphase (line 61)
            chat = constructphase(s,g,a,tol,phaseconv);

Error in test_all_ltfat (line 112)
        test_failed=feval(['test_',tests_todo{ii}]);

**Comment by germknoedlspeck** [comment]
Trying again on a different machine, getting the same error message.

OS: Windows 10 Education, Version 20H2, OS build 19042.1706
Matlab R2018a

**Comment by nholighaus** [comment]
Dear everyone,

OS: Linux Mint 19.3; Kernel: 5.4.0-107-generic
Hardware: Intel© Core™ i7-2600 CPU, 14GB RAM
MATLAB: MATLAB R2017a

I have the following issues:

======================
Expected(?)/Minor: 'demo_blockproc_slidingsgram' worked after manually specifying the device ID like this:

demo_blockproc_slidingsgram(gspi,'devid',id);

which I think is not unexpected behavior under Linux.
======================
test_all_ltfat report:

18 TESTS FAILED
The following test scripts contained failed tests
   test_multidgtrealmp double
   test_multidgtrealmp single

---
Specifically, I could find:

MULTIDGTREALMP MAXIT  dict:  1 FAILED
MULTIDGTREALMP MAXIT  dict:  1 FAILED
MULTIDGTREALMP MAXIT  dict:  1 FAILED
MULTIDGTREALMP MAXIT  dict:  2 FAILED
MULTIDGTREALMP MAXIT  dict:  2 FAILED
MULTIDGTREALMP MAXIT  dict:  2 FAILED
MULTIDGTREALMP MAXIT  dict:  3 FAILED
MULTIDGTREALMP MAXIT  dict:  3 FAILED
MULTIDGTREALMP MAXIT  dict:  3 FAILED

I guess that these 9 tests failed for both double and single precision, but the first one is not visible in the command history anymore.
=======================

**Comment by germknoedlspeck** [comment]
> Hi!
> 
> OS: Windows 10 Pro, Version 21H2, OS build 19044.1706 Matlab R2021b
> 
> After a few minutes when starting start_all_ltfat, I get the following error message (including the last header in the cmd window before the error message):
> 
> =================== TEST_CONSTRUCTPHASE ====================== Unrecognized function or variable 'comp_heapint'.
> 
> Error in constructphase (line 158) newphase=comp_heapint(abss,tgrad,fgrad,a,tol(1),flags.do_timeinv);
> 
> Error in test_constructphase (line 61) chat = constructphase(s,g,a,tol,phaseconv);
> 
> Error in test_all_ltfat (line 112) test_failed=feval(['test_',tests_todo{ii}]);

Edit (24-05-2022) for this machine:

19 TESTS FAILED
The following test scripts contained failed tests
   test_multidgtrealmp double
   test_multiwin single
   test_multidgtrealmp single

**Comment by germknoedlspeck** [comment]
> > Hi!
> > OS: Windows 10 Pro, Version 21H2, OS build 19044.1706 Matlab R2021b
> > After a few minutes when starting start_all_ltfat, I get the following error message (including the last header in the cmd window before the error message):
> > =================== TEST_CONSTRUCTPHASE ====================== Unrecognized function or variable 'comp_heapint'.
> > Error in constructphase (line 158) newphase=comp_heapint(abss,tgrad,fgrad,a,tol(1),flags.do_timeinv);
> > Error in test_constructphase (line 61) chat = constructphase(s,g,a,tol,phaseconv);
> > Error in test_all_ltfat (line 112) test_failed=feval(['test_',tests_todo{ii}]);
> 
> Edit (24-05-2022) for this machine:
> 
> 19 TESTS FAILED The following test scripts contained failed tests test_multidgtrealmp double test_multiwin single test_multidgtrealmp single

Edit (25-05-2022) for this machine. Apologies, I forgot to run (3) and (4) before 😬:

test_all_ltfat
> ALL TESTS PASSED

%%%%%%%%

demo_blockproc_slidingsgram(gspi);
> Error using demo_blockproc_header (line 21)
> demo_blockproc_slidingsgram: playrec or portaudio are not properly compiled.
> 
> Error in demo_blockproc_slidingsgram (line 29)
> if demo_blockproc_header(mfilename,nargin)

%%%%%%%%

mulaclab(gspi,44100);
I tried cutting a piece from the spectrum and playing both the original and modified version - everything works!

**Comment by germknoedlspeck** [comment]
Edit #2 (25-05-2022) for this machine: everything works now 👍

**Comment by nholighaus** [comment]
With the latest package, all tests pass for me:

OS: Linux Mint 20.2; Kernel: 5.4.0-91-generic
Hardware: Intel© Core™ i7-6700HQ CPU, 8GB RAM
MATLAB: MATLAB R2017a

**Comment by nperraud** [comment]
On macos Catalina 10.15.7
- MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
- 2.5 GHz Dual-Core Intel Core i7, 16 GBRAM

Compilation works and 
1 TESTS FAILED
The following test scripts contained failed tests
   test_multiwin single

**Comment by allthatsounds** [comment]
Many thanks to you all :) !
(the test_multiwin sometimes exceeds the testing threshold since it's input is random)
