### ISSUE TITLE
[Question] Phase Vocoder Done Right

### ISSUE THREAD

**Issue by jakemumu** [ltfat/ltfat#139]
Hey! I'm looking for an implementation of the Phase Vocoder Done Right so I could run some test audio through it -- is there an implementation in this toolbox somewhere?

**Comment by nholighaus** [comment]
Check out demo_phasevocoder.m and phasevocoder.m in the PhaseRet (Sub-)Toolbox:

https://github.com/ltfat/phaseret/

If you have any more questions regarding the PVDR, please contact me directly or ask on the PhaseRet Github page.
