### ISSUE TITLE
Rewrite ltfatarghelper in C

### ISSUE THREAD

**Issue by susnak** [ltfat/ltfat#14]
It really slows things down when it is called aover and over

**Comment by susnak** [comment]
There is a problem with the matlab function dbstack which does not work from MEX and it is really necessary.

**Comment by susnak** [comment]
I probably have a fully working ltfatarghelper as a MEX function, I just cannot find a way how to test it thoroughly. 
Last thing that came to my mind was to replace each occurrence of ltfatarghelper with something like this:

E.g. in dgt.m

Replace this

[flags,kv,L]=ltfatarghelper({'L'},definput,varargin);

with

oldpath = pwd;
cd(ltfatbasepath);
% This calls ltfatarghelper.m
[flags,kv,L]=ltfatarghelper({'L'},definput,varargin);
cd([ltfatbasepath,filesep,'mex']);
% This calls mex/ltfatarghelper.mex...
[flags2,kv2,L2]=ltfatarghelper({'L'},definput,varargin);
if ~isequal(flags,flags2) || ~isequal(kv,kv2) || ~isequal(L,L2)
     error('ltfatarghelper failed in %s',upper(mfilename));
     cd(oldpath);
end
cd(oldpath);

It could be done automatically via a Python script and it would test every use case.
What do you think about this idea?

**Comment by psoenderg** [comment]
I think it would work, but I would test it first by simply removing the script code, and then running the entire tester and regenerate all the documentation, but perhaps you have already done that? That would probably catch most bugs just by provoking them.

**Comment by susnak** [comment]
So I have done both and it seems to be working. The speedup varies, the C verion is even slightly slower in some cases, but I have not done any thorough comparision.
At first it seemed that the speedup will be around 10, but the C version has so many checks, that it is now on average about 4. I would like to profile it somehow, but it is quite hard to do.
