### ISSUE TITLE
Problem when compiling ltfatmex mingw32-make ...libltfat No such file or directory

### ISSUE THREAD

**Issue by ComputerCrazyCookie** [ltfat/ltfat#140]
Hi,

I am getting this error compiling ltfatmex on windows:
>> ltfatmex
========= Compiling libltfat ==============
   ...using libfftw3-3.dll from ltfat/mex.
   ...using libfftw3f-3.dll from ltfat/mex.
Error using ltfatmex (line 250)
Failed to build LTFAT libs:
 mingw32-make -C ..\..\libltfat build/libltfat.dll OPTCFLAGS="-DMATLABFORTRAN
 -DDLL_EXPORT_SYMBOLS -DLTFAT_LARGEARRAYS" BLASLAPACKLIBS="-L\"C:\Program
 Files\MATLAB\R2021a\bin\win64\"  -lmwlapack -lmwblas" FFTWLIBS="-L../mex -l:libfftw3-3.dll
 -l:libfftw3f-3.dll" MINGW=1
mingw32-make: *** ....libltfat: No such file or directory.  Stop.
Makefile_mingw:18: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

I have tried to manually addpath libltfat, but it makes no difference.

Hopefully you have an idea.

Regards

**Comment by ComputerCrazyCookie** [comment]
Oops now I found the installation instructions. Worked!

**Comment by allthatsounds** [comment]
Just meant to answer you...perfect! :)

**Comment by ComputerCrazyCookie** [comment]
That is very kind. Thank you! :)
