### ISSUE TITLE
Issues in documentation and code of filterbankconstphase

### ISSUE THREAD

**Issue by nholighaus** [ltfat/ltfat#141]
1) For the choice of phase-magnitude relations, the documentation of filterbankconstphase offers the flags 'filterbank' and 'wavelet', while the code seems to use 'gabor' and 'wavelet'. I did not find anything in the code that hints at 'gabor' and 'filterbank' being used synonymously, but might have overlooked something. I think 'gabor'/'wavelet' is preferable as it hints at the choice of phase-magnitude relation, even though calling it 'filterbank' provides a more direct link to ltfatnote051, where the method was introduced. 

2) The documentation states 

%   Example
%   -------
%
%   The following example shows basic usage

followed by absolutely nothing. An example should be added.

**Comment by nholighaus** [comment]
Since noone chimed in, I'll just rename all instances of 'filterbank' to 'gabor'

**Comment by allthatsounds** [comment]
added example with ltfat 2.6.0
