### ISSUE TITLE
Typos in the LTFAT documentation

### ISSUE THREAD

**Issue by rajmic** [ltfat/ltfat#142]
Hi guys,

at
http://ltfat.org/doc/gabor/isgramreal.html
the documentation says that the input argument is s, however the list below speaks about c.

http://ltfat.org/doc/gabor/idgtreal.html
says that "idgtreal(c,g,a,M) computes the Gabor expansion of the input coefficients c", which I find misleading.
In the following sentence, "c is assumed to be the positive frequencies of the Gabor expansion", which is also not quite precise statement :)

Thank you and good luck to LTFAT,
Pavel

**Comment by allthatsounds** [comment]
Thanks for pointing this out! We will try and fix it with the next release!

**Comment by allthatsounds** [comment]
done in ltfat 2.6.0
