### ISSUE TITLE
phase shift by dctresample.m when upsampling?

### ISSUE THREAD

**Issue by timvanzon** [ltfat/ltfat#146]
% demo of bug
% ltfat-2.3.1
% octave 4.2.2, 
% OS: Ubuntu 16.04
pkg load ltfat 
sampleFreqOri = 4;
sampleFreqNew = 6;
ntOri=24;
tOri = ([0:ntOri-1]./sampleFreqOri) .'; % col vec with the time-axis 
dat = sin(0.5.*2*pi*tOri);  % sine with freq of 0.5 hz
ntNew= size(dat,1).*sampleFreqNew./sampleFreqOri; % number of samples in upsampled signal
tNew= ([0:ntNew-1]./sampleFreqNew ).';
res=dctresample(dat,ntNew,dim=1)
resFFT = fftresample(dat,ntNew,dim=1);

figure;
plot(tOri, dat, '-+');
hold on 
plot(tNew,res,'-rx')
plot(tNew, resFFT, '-oc')
grid on
legend('original', 'dctresample', 'fftresample')
xlabel('Time [s]')
title('illustration of phase shift by dctresample when upsampling?')

this produces:
![image](https://user-images.githubusercontent.com/36953948/236403263-4fb12191-638c-4306-b633-06f5939afcb5.png)

So there seems to be a phase shift in the data upsampled by dctresample.m, but not in the data upsampled by fftresample.m
the difference is clearly seen at t==0, but also at the peaks of the sine, there is an amplitude difference with dctresample.m that is not present with fftresample.m
(The time-shift does not seem to be exactly 1 sample)

>> which dctresample
'dctresample' is a function from the file /home/zon/octave/ltfat-2.3.1/fourier/dctresample.m

**Comment by allthatsounds** [comment]
Hi, this phase shift is to be expected, since the DCT and the FFT differ in the type of basis functions they use for decomposing the input signal. Here is a concise explanation: https://ccrma.stanford.edu/~jos/st/Discrete_Cosine_Transform_DCT.html 
Let us know if you have further questions!

**Comment by timvanzon** [comment]
@allthatsounds thank you for your answer.
I changed the sin to cos, as that should be easier to represent with cosines, but I still see a phase shift.:

![image](https://user-images.githubusercontent.com/36953948/236753204-d0582f14-b919-407b-8c5b-ecccaa3daa00.png)

and I see:
>> max(res)
ans =  1.0128
>> min(res)
ans = -0.99233

so it seems to have a slight offset (about 1%) , but the mean=1e-17, so I guess that might be due to the limited number of samples in my example and that my last point is not at the same value as my first point.

Thanks again for responding!
