### ISSUE TITLE
As a student I would like to learn about MFCC

### ISSUE THREAD

**Issue by psoenderg** [ltfat/ltfat#15]
- Implement a function to compute MFCC (Mel Frequency Cepstrum Coefficients) for machine recoqnition of speech on top of a Gabor filterbank or on top of the block processing framwork
- In the function, make an example visualizing the coefficients using plotdgtreal

**Comment by lostanlen** [comment]
@psoenderg are you aware of the RASTAMAT toolbox, developed by Columbia U ?
 http://labrosa.ee.columbia.edu/matlab/rastamat/
