### ISSUE TITLE
comp_gdgt currently does not work

### ISSUE THREAD

**Issue by allthatsounds** [ltfat/ltfat#162]
it relies on comp_dgt, and the parameter passing is currently broken.
however, it is also a ghost function that is not called from anywhere within the toolbox (except for its tester). 

decide what to do with it and make it work.

**Comment by nholighaus** [comment]
I must admit that I do not quite see the purpose of the function and it also seems that it is only half-way implemented: The input parameter 'c_w' (window centering) is documented, but not used. The one potentially interesting aspect (explored in the tester) is that it allows fractional offsets of time-frequency shifts and/or custom phase conventions, but I'd much prefer to separate these two conceptually. 

Fractional TF offsets are trivially realized by fractional TF shifts of the window pre-dgt-ing, but generally break LTFAT conventions (in a way), by introducing complex exponentials with discontinuities, something that we have a workaround for in the filterbank module, but not for dgts.

With regard to phase conventions, I am usually all for generality, but I would rather just have the 'symphase' convention (already present in e.g.. gabphasederiv) available in dgt(real), such that all three somewhat established phase conventions are represented and deprecate comp_gdgt.

**Comment by allthatsounds** [comment]
moved to deprecated.
