### ISSUE TITLE
Release LTFAT 2.6.0

### ISSUE THREAD

**Issue by allthatsounds** [ltfat/ltfat#163]
Dear all,
it's again the time of the year where I am asking for your help.
LTFAT 2.6.0 is (nearly) out, please test it.
As for the last time, I shamelessly copied the steps I'd ask you to follow from
Zdeneks previous releases below.

Thanks,
Clara

Please report your results as a reply to this ticket. Please also include your OS and whether you are using Matlab or GNU Octave.

Matlab users:
-----------------

1) Get the appropriate release package from https://github.com/ltfat/ltfat/releases/tag/v2.6.0

2)  Make sure that your regular LTFAT installation is not in the search path and run the following:
```
ltfatstart
ltfatmex % (not on Windows)
ltfatmex playrec % (not on Windows)
test_all_ltfat % This might take a long time
```
3) Also run 
```
demo_blockproc_slidingsgram(gspi); 
```
4) And this too
```
mulaclab(gspi,44100);
```
This should open a GUI and is should be possible to select some area using the mouse (right click finishes the selection). Then click the Apply button and a second plot should appear with the selected area removed.

**Comment by nholighaus** [comment]
On Linux Mint 20.2 Cinnamon, MATLAB R2017a, I can compile everything without error and all tests are successful. Mulaclab works fine as well. 

Ad 3) This only works for me if I manually specify the output device using the 'devid' key-value pair (e.g., default, ALSA, id obtained via blockdevices). I get the following warning/error for the block processing framework if I do not (the warning obviously persists in the case with specified devid as well): 

Warning: BLOCK: Sampling rate not specified. Using default value 44100 Hz. 
> In block (line 265)
  In demo_blockproc_slidingsgram (line 43) 
Error using demo_blockproc_slidingsgram (line 48)
Error using block>failedInit (line 638)
Error using playrec
Init failed to open PortAudio stream
{PortAudio Error [-9985]: Device unavailable}

**Comment by allthatsounds** [comment]
Thanks to all, it's done! :)
