### ISSUE TITLE
Fix title of insdgfb

### ISSUE THREAD

**Issue by psoenderg** [ltfat/ltfat#18]
The description of insdgfb in the Contents.m file still says "Say what?"

Figure out something better than Nonstationary Gabor filterbank synthesis

**Comment by susnak** [comment]
Well, I did something a bit different:
https://github.com/ltfat/ltfat/commit/244d89f14aece0a2724817bc070a6f5b5988d8cb

**Comment by psoenderg** [comment]
Much, much better! Closing it.
