### ISSUE TITLE
Out-of-date link to documentation

### ISSUE THREAD

**Issue by rajmic** [ltfat/ltfat#193]
Hi,
by chance I found a wrong link in/to the documentation. The link to LTFAT note 17 from
http://ltfat.org/doc/fourier/nextfastfft.html
leads to an obsolete webpage
https://ltfat.sourceforge.net/notes/ltfatnote017.pdf
Best, Pavel

**Comment by allthatsounds** [comment]
Thanks for pointing that out! I fixed it in the sources and the new link will be online with the next release.
