### ISSUE TITLE
Recreate the sourceforge homepage on Github pages

### ISSUE THREAD

**Issue by psoenderg** [ltfat/ltfat#20]
https://pages.github.com/

This looks like it would fit us perfectly, and we could avoid the sourceforge cludge. The output from mat2doc would go to a git repository with a gh-pages branch, and when we commit, the homepage updates automatically. No more rsync stuff.

**Comment by susnak** [comment]
Yep, but We have to rewrite the pages back to html.

**Comment by psoenderg** [comment]
Try the 'html' target of mat2doc (instead of 'php'), I don't know what state it is currently in. It should be possible to fix it up with a relative minor effort.

**Comment by psoenderg** [comment]
I have just tried running the 'html' target of mat2doc, and everything seems to work out of the box.

**Comment by susnak** [comment]
OK, I will try to migrate the pages soon. There is now a new repository for holding the webpage source and the pages are accessible from http://ltfat.github.io/

**Comment by susnak** [comment]
I want to somehow avoid copying the common parts of code to each page. Any ideas how to do that without server side scripting?
I have found some Javascript frameworks which could be used for that, but they are generally capable of much more so it seems like an overkill to use them.

**Comment by psoenderg** [comment]
Actually, I have never written a single line of Javascript. Is there anything you can reuse from the bootstrap framework? Otherwise I would guess at jquery.load()

**Comment by susnak** [comment]
There is now a preliminary version of the pages: http://ltfat.github.io/
I used the jquery.load() function to popolate the top navigation menu, footer and part of the header. Unfortunatelly it is not possible to include the header as whole for several reasons, but I am quite satisfied with how it is now.

It can be used like this:
<div class='include' file='./include/footer.html'></div>
and the script popolates content of that div usinf footer.html
Moreover, any occurence of #BASEURL# in href of <a> and src of <img> will be replaced by a path from a global variable.

I also included a skeleton.html page to show what can be included so far.

**Comment by susnak** [comment]
And I also moved to the newest Boostrap, which is slightly incompatible with the old pages so that is why the menu looks strange (I was not able to center it).

**Comment by psoenderg** [comment]
I can confirm that it works!

While you are at it, let's do something about this sentense on the front page: "LTFAT is developed at CAHR, Technical University of Denmark, ARI, Austrian Academy of Sciences and LATP, Universite de Provence." 

Unless you can come up with something better, I propose just to erase it. We are now an international open source project, and not something limited to a few universitites.

**Comment by susnak** [comment]
Done.

**Comment by susnak** [comment]
Would it make sense to move the  base ltfat routines from
http://ltfat.sourceforge.net/doc/
to e.g. here?
http://ltfat.sourceforge.net/doc/root/
That would mean that no module in ltfat could be called root. The same already holds for start and include.

**Comment by psoenderg** [comment]
Sure, I have no objections.

**Comment by jvnv** [comment]
I think it definitely makes sense. I see more positive effects than negative.

**Comment by susnak** [comment]
So the pages are mostly done. Could you please help me testing it in different browsers?

**Comment by jvnv** [comment]
I have tested it in Google Chrome, Safari and Firefox. They all work the same and it looks good.

One personal objection: I don't like the audio file of 'greasy' under the spectrogram of it on the homepage.

**Comment by susnak** [comment]
>One personal objection: I don't like the audio file of 'greasy' under the spectrogram >of it on the homepage.

Removed. It does not show consistently across browsers anyway.

**Comment by psoenderg** [comment]
The markup for the input and output parameters is too heavy for my taste (tested in Chrome on Windows 7): The example is DGT:

![image](https://cloud.githubusercontent.com/assets/10614141/6868409/b3355990-d48b-11e4-95a7-dabea826776e.png)

**Comment by susnak** [comment]
I don't even know where it came from. I guess bootstrap3 has slightly different styles.

**Comment by psoenderg** [comment]
It's fugly in Explorer 9 (but who cares):
![image](https://cloud.githubusercontent.com/assets/10614141/6868530/a113a482-d48c-11e4-8425-b3cf40810995.png)

**Comment by jvnv** [comment]
The text "LTFAT is developed at CAHR, Technical University of Denmark, ARI, Austrian Academy of Sciences and LATP, Universite de Provence" is now removed from the homepage. Maybe the logos associated with these institutions should also be removed.

**Comment by susnak** [comment]
I have updated the homepage and I would like to close this. 
Could you please check whether the doc page http://ltfat.github.io/doc/ looks ok?
There is a new function selector and the View the code/help should now persist when a different function is selected.

**Comment by jvnv** [comment]
I think it looks good in general, but personally I don't really like the
font in which the code commands, e.g., 'dgt', are represented. This font is
different from the one it always was, isn't it?

**Comment by psoenderg** [comment]
If I use the "Go to function" dropdown to go to another function (which
btw looks really good and is well organized), then I cannot use it again
immidiatly. Sometimes I can after waiting or clicking around, but I cannot
figure what the exact condition is to make it work again.

Cheers,
Peter

**Comment by susnak** [comment]
The style is exactly the same as before but it is true that it could be 
better.

**Comment by susnak** [comment]
Do you think the browser cache might be causing that?
What browser do you use?

**Comment by psoenderg** [comment]
I used chrome on Windows 

On 11. aug. 2015 17.26.55 CEST, "Zdeněk Průša" <notifications@github.com> wrote:
>Do you think the browser cache might be causing that?
>What browser do you use?
>
>On 08/07/2015 12:37 PM, Peter L. Søndergaard wrote:
>> If I use the "Go to function" dropdown to go to another function
>(which
>> btw looks really good and is well organized), then I cannot use it
>again
>> immidiatly. Sometimes I can after waiting or clicking around, but I
>cannot
>> figure what the exact condition is to make it work again.
>>
>> Cheers,
>> Peter
>>
>>
>>
>> > I think it looks good in general, but personally I don't really
>like the
>> > font in which the code commands, e.g., 'dgt', are represented. This
>font
>> > is
>> > different from the one it always was, isn't it?
>> >
>> > On Thu, Aug 6, 2015 at 7:58 PM, Zdeněk Průša
><notifications@github.com>
>> > wrote:
>> >
>> >> I have updated the homepage and I would like to close this.
>> >> Could you please check whether the doc page
>http://ltfat.github.io/doc/
>> >> looks ok?
>> >> There is a new function selector and the View the code/help should
>now
>> >> persist when a different function is selected.
>> >>
>> >> —
>> >> Reply to this email directly or view it on GitHub
>> >> <https://github.com/ltfat/ltfat/issues/20#issuecomment-128459298>.
>> >>
>> >
>> >
>> > ---
>> > Reply to this email directly or view it on GitHub:
>> > https://github.com/ltfat/ltfat/issues/20#issuecomment-128667696
>>
>>
>> —
>> Reply to this email directly or view it on GitHub 
>> <https://github.com/ltfat/ltfat/issues/20#issuecomment-128669412>.
>>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ltfat/ltfat/issues/20#issuecomment-129929529

-- 
Sendt fra min Android telefon med K-9 Mail. Undskyld hvis jeg er lidt kortfattet.

**Comment by jvnv** [comment]
I don’t really have a problem with that. I tried it on several browsers (chrome, safari, mozilla firefox) on OS X. However, it seems the page of the function you want to access should be loaded before you can access another function, but I don’t think this is really a problem.


> Op 11 aug. 2015, om 17:59 heeft Peter L. Søndergaard <notifications@github.com> het volgende geschreven:
> 
> I used chrome on Windows 
>

**Comment by susnak** [comment]
Ok, I am closing this.
I will keep the sourceforge homepage in sync.
