### ISSUE TITLE
Can't find beat.wav

### ISSUE THREAD

**Issue by psoenderg** [ltfat/ltfat#23]
I try to run demo_blockproc_effetcs, but it cannot find beat.wav.

**Comment by susnak** [comment]
Well, the morphing effect only sounds nice for a specific background sound, but I did not want to include it in LTFAT so therefore there is the warning. Any wav file called beat.wav in the search path is sufficient.

**Comment by psoenderg** [comment]
Please just include it. My intuitive thought when running the demo was that something was broken, and I don't know how to make a good beat.wav file, so I would much prefer for it to be included.
