### ISSUE TITLE
Compilation on 32 bit Matlab on Windows 64 bit

### ISSUE THREAD

**Issue by psoenderg** [ltfat/ltfat#25]
I have a user that tried to compile using 32 bit Matlab on Windows using TDM-GCC-32 (version 4.9). 

He gets the following:

>> ltfatmex
========= Compiling libltfat ==============
   ...using libfftw3-3.dll from ltfat/mex.
   ...using libfftw3f-3.dll from ltfat/mex.
Error using ltfatmex (line 221)
Failed to build LTFAT libs:
gcc -shared -Wl,--dll ddgt.o ddgt_fac.o ddgt_fb.o ddgt_multi.o
ddgt_ola.o ddgt_shear.o ddgt_walnut.o ddgtreal_fac.o ddwilt.o didwilt.o
dwmdct.o diwmdct.o dfilterbank.o difilterbank.o dheapint.o didgt.o
didgt_fac.o didgt_fb.o diwfac.o dpfilt.o dreassign.o dspread.o dwfac.o
dwindows.o dwinmanip.o dltfat_complexindependent.o ddgt_shearola.o
ddct_ci.o ddst_ci.o dfftreal.o c-safe-memalloc.o integer_manip.o
dltfat_blaslapack.o dgabdual_fac.o dgabtight_fac.o
dltfat_complexindependent_bl.o  \
-o ../lib/ltfat.dll -static-libgcc -L../mex -l:libfftw3-3.dll
-L"\\erhmfapp01\Mathworks\MatlabR2013b\bin\win32"  -lmwlapack -lmwblas
ddgt.o: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
Makefile_mingw:48: recipe for target 'double_shared' failed
mingw32-make: *** [double_shared] Error 1

>> ltfatmex playrec
========= Compiling PLAYREC ===============
   ...using portaudio_x64.dll from ltfat\thirdparty\Playrec.
Error using ltfatmex (line 346)
Failed to build PLAYREC:
gcc -static-libgcc -fPIC -std=c99 -O3 -Wall -shared -DMATLAB_MEX_FILE
-DHAVE_PORTAUDIO
-I"\\erhmfapp01\Mathworks\MatlabR2013b/extern/include" -I.
-I../../src/thirdparty mex_dll_core.c pa_dll_playrec.c ltfatresample.c
-Wl,--no-undefined -L.
-L"\\erhmfapp01\Mathworks\MatlabR2013b/bin/win32" -lmex -lmx -lm
-l:portaudio_x64.dll -o playrec.mexw32
mex_dll_core.c:1:0: warning: -fPIC ignored for target (all code is
position independent)
/*
^
pa_dll_playrec.c:1:0: warning: -fPIC ignored for target (all code is
position independent)
/*
^
ltfatresample.c:1:0: warning: -fPIC ignored for target (all code is
position independent)
/*
^
portaudio_x64.dll: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
Makefile_unix:35: recipe for target 'all' failed
mingw32-make: *** [all] Error 1

**Comment by susnak** [comment]
Is that 32bit Matlab running on 64bit Windows?

**Comment by psoenderg** [comment]
Yes, it is 32bit Matlab on 64bit Windows. I have fixed the title

**Comment by susnak** [comment]
Then he should try the ltfat-2.0.0-win32.zip package and not ltfat-2.0.0-win64.zip, but
it was only tesed on 32 bit Windows...
Link: https://sourceforge.net/projects/ltfat/files/ltfat/2.0/

What the error messages mean:
========= Compiling libltfat ==============
ddgt.o: file not recognized: File format not recognized
All the object files were compiled but probably but linker is invoked with different bitness or the other way around.

========= Compiling PLAYREC ===============
portaudio_x64.dll: file not recognized: File format not recognized
This obviously tries to link a 64bit library. ltfat-2.0.0-win32.zip already contains portaudio compiled as a 32 bit library.

**Comment by psoenderg** [comment]
Feedback from the user: The block processing framework works fine using the ltfat-2.0.0-win32.zip on a 32 bit Matlab on 64 bit Windows.
