### ISSUE TITLE
firwin and 'sqrtrect'

### ISSUE THREAD

**Issue by susnak** [ltfat/ltfat#27]
'sqrtrect' is not implemented, but it is still in the help.

**Comment by psoenderg** [comment]
Ok, I looked at it and here is the resolution:

* Delete sqrtrect from the help

* Delete halfrect and sqrthalfrect from the code

* Change the help for 'rect' to say: "Forms a PU if the order is odd.", this is more accurate.

I wanted to include the halfrect and sqrthalfrect windows for completeness, but they are useless and not interesting, not even for teach.

... and there is a bug in the implementation for halfrect for odd orders.

So just clean up

**Comment by psoenderg** [comment]
Sorry, I didn't make myself clear: Delete the **entire code** for halfrect, halfsquare, sqrthalfrect and sqrthalfsquare.
