### ISSUE TITLE
Merge the Wigner-Ville distribution into the master branch.

### ISSUE THREAD

**Issue by jvnv** [ltfat/ltfat#30]
The Wigner-Ville distribution is one of the quadratic time-frequency distributions that will be added to LTFAT - see issue 7.
Until now the only quadratic time-frequency distribution that is in the master branch of LTFAT is the Rihaczek distribution. The discrete definition of this distribution is so straightforward that there aren't any problems with it: it perfectly satisfies the expected properties.

The next quadratic time-frequency distribution that should be added is the Wigner distribution. This should be the first since all other quadratic time-frequency distributions can be derived from this distribution through the general class of quadratic time-frequency distribution, which is based on the Wigner distribution. 
In the quadratic branch is now a routine that computes the Wigner distribution: dwvd. (Strictly speaking this is the Wigner-Ville distribution since it computes the Wigner distribution of the analytic representation of the function to be analyzed). This routine seems to be appropriate for the definition of the general class of quadratic time-frequency distributions, which is available as 'dqtfd' in the quadratic branch. Other quadratic distributions are already derived from it: Choi-Williams distribution (dcwd), Margenau-Hill distribution (dmhd) and Born-Jordan distribution (dbjd). However, this routine could probably better be seen as an "approximation" of the definition of the Wigner-Ville distribution on the real-line rather than a pure finite, discrete definition of the Wigner-Ville distribution. 
There is also a purely discrete definition of the Wigner distribution. This version is based on the definition of the Wigner distribution on locally compact abelian groups. However, the routine that computes this version of the Wigner distribution doesn't correspond to the 'intuitive' idea that is associated with the Wigner distribution on the real-line. Aside that, I am not sure if there exist finite, discrete definitions of the other quadratic time-frequency distributions.

We should decide which version of the Wigner distribution we prefer. Another option is to include them both.

**Comment by psoenderg** [comment]
We should include both of them, with appropriate naming. This is the same that we have done for the Hermite functions, the fractional Fourier transform and the fractional splines.

You should not abbreviate the names so much, we have moved away from this. It is almost impossible for outside people to decipher the abbreviatations. Please call it something like "dwignerdist" or "choiwilliams" or something. It does not matter that the names are longer, these are not functions that will be called at lot.

I would propose some kind of prefix to tell the sampled, continuous distributions from the truly discrete ones.

**Comment by jvnv** [comment]
Perfect, then I will also add the finite, discrete definition of them later.

You are right with regard to the naming. I will rename the distributions when merging them into the master branch. The discrete Rihaczek distribution, the only distribution in the master branch right now, is already called "drihaczekdist", so that is completely consistent with your suggestion. 

I propose to use the prefix "d" only in the case of the finite, discrete definition. This seems to be consistent with other functions in LTFAT. So, the routine that "approximates" the definition of the Wigner distribution on the real-line will be called something like "wignervilledist" and the routine for the finite, discrete definition of it will be called "dwignervilledist".

**Comment by psoenderg** [comment]
I really like that approach: Keep the clean name for the sampled, continuous distribution (which is what people expect to find), and use the "d" for the other, which is probably most relevant for teaching and education.

**Comment by jvnv** [comment]
Perfect. Then I will do it like that.

One last thing: What about the formulae to display? The main routines I have until now correspond "more or less" to formulae, and are also tested against this formulae through test and reference routines. The "more or less" part is based on the fact that, for example, it isn't given explicitly how the "kernel" is computed. However, it is given explicitly that the distribution corresponds to the discrete Fourier transform of the "kernel" of the analytic representation of the analysed function (see for an example the formula in the routine called 'dwvd', the Wigner-Ville distribution).

I prefer to do it this way, so to give a glimpse of how it is computed. However, I don't know if this is a way that will be appreciated. It seems that for all the "approximations" that are now in LTFAT there isn't a formula.
