### ISSUE TITLE
Change nonstationary into non-stationary in the documentation

### ISSUE THREAD

**Issue by psoenderg** [ltfat/ltfat#33]

**Comment by psoenderg** [comment]
Apply the patch here: https://gist.github.com/psoenderg/69d2c740b2e21b1e6d89

**Comment by psoenderg** [comment]
@jvnv : I created a Github issue on the non-stationary cleanup and assigned it to @susnak . Let's see if he will apply it :-)

**Comment by psoenderg** [comment]
Here is another patch to fix the capitalized non-stationary: https://gist.github.com/psoenderg/bd9ad3b69c1991e31222

It might not apply cleanly.

**Comment by susnak** [comment]
Done. It did not apply cleanly, but at least a learned about three-way merge...
