### ISSUE TITLE
Make the LTFAT homepage mobile friendly

### ISSUE THREAD

**Issue by psoenderg** [ltfat/ltfat#36]
Google has started ranking pages that are not mobile friendly lower in their search rankings. 

There is an article here: http://www.itworld.com/article/2912315/are-you-ready-for-googles-mobilegeddon-on-tuesday.html

and there is a test tool here:https://www.google.com/webmasters/tools/mobile-friendly/

We currently fail the test.

**Comment by susnak** [comment]
http://ltfat.sourceforge.net/ fails the test but http://ltfat.github.io/ doesn't.

**Comment by psoenderg** [comment]
Nice! It looks ugly, but passes the test. So does /doc and /notes. I will close this issue, because the issue will be gone when we are finished transferring to Github.
