### ISSUE TITLE
wavread has been removed from Matlab 2015B

### ISSUE THREAD

**Issue by psoenderg** [ltfat/ltfat#43]
We should remove all instances of wavread and replace with audioread.

"greasy" fails with an error.

**Comment by susnak** [comment]
Yes, but it is much slower than wavread, which is a problem in the blockproc. framework.

**Comment by psoenderg** [comment]
Damm. But at least we can remove it from all the signal functions.

**Comment by nholighaus** [comment]
And will also break compatibility with older versions of matlab. Definitely 2011b backwards maybe newer ones, too. No clue when they introduced audioread.

Von meinem Xperia™-Smartphone  gesendet

**Comment by susnak** [comment]
Maybe we could borrow readwav.m from voicebox:
http://www.ee.ic.ac.uk/hp/staff/dmb/voicebox/doc/voicebox/readwav.html
and simplify it slightly.

**Comment by susnak** [comment]
audioread was introduced in 2012b

**Comment by susnak** [comment]
So readwav reads anything I have tried and it is even much faster than wavread.

**Comment by psoenderg** [comment]
Then let's include it! 

On 8. okt. 2015 10.15.42 CEST, "Zdeněk Průša" <notifications@github.com> wrote:
>So readwav reads anything I have tried and it is even much faster than
>wavread.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ltfat/ltfat/issues/43#issuecomment-146452559

-- 
Sent from my VIC 20 with K-9 Mail.

**Comment by psoenderg** [comment]
I think this situation sucks: Mathworks deprecating its own software after just 3 years. 

I think we should have a wrapper that calls wavread if it is available, otherwise calls Audioread. Ltfatwavread or something. Is that was readwave does? Cheers, Peter. 

On 8. okt. 2015 06.08.13 CEST, "Zdeněk Průša" <notifications@github.com> wrote:
>audioread was introduced in 2012b
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ltfat/ltfat/issues/43#issuecomment-146414390

-- 
Sent from my VIC 20 with K-9 Mail.

**Comment by susnak** [comment]
Dne 8.10.2015 v 21:02 Peter L. Søndergaard napsal(a):
> I think this situation sucks: Mathworks deprecating its own software 
> after just 3 years.
>
> I think we should have a wrapper that calls wavread if it is 
> available, otherwise calls Audioread. Ltfatwavread or something. Is 
> that was readwave does? Cheers, Peter.
No, readwav is a complete pure-Matlab implementation. It worked with all 
wav files I tried.
>
> On 8. okt. 2015 06.08.13 CEST, "Zdeněk Průša"

**Comment by susnak** [comment]
In the repository, there is now a function called wavload. It should be even compatible with Octave. Could you please test it on Matlab and Octave with some of your wav files? Thanks
