### ISSUE TITLE
warning in Matlab 2015b

### ISSUE THREAD

**Issue by psoenderg** [ltfat/ltfat#44]
demo_blockproc_slidingerblets runs very slowly, because it continuously prints warnings to the screen:

 In blockread (line 190)
  In demo_blockproc_slidingerblets (line 71) 
Warning: The function 'block_interface' returned an mxArray with non-temporary
scope. 

> In blockread (line 192)
>   In demo_blockproc_slidingerblets (line 71) 
> Warning: The function 'block_interface' returned an mxArray with non-temporary
> scope. 
> In blockread (line 192)
>   In demo_blockproc_slidingerblets (line 71) 
> Warning: The function 'block_interface' returned an mxArray with non-temporary
> scope. 
> In blockana (line 68)
>   In demo_blockproc_slidingerblets (line 74) 
> Warning: The function 'block_interface' returned an mxArray with non-temporary
> scope. 
> In blockana>loadOverlap (line 215)
>   In blockana (line 148)
>   In demo_blockproc_slidingerblets (line 74) 
> Warning: The function 'block_interface' returned an mxArray with non-temporary
> scope.

**Comment by susnak** [comment]
A quick fix is to delete mex/block_interface.mex...
The Matlab version is probably not much slower.

**Comment by psoenderg** [comment]
I fixed it, I installed r2011b

On 7. okt. 2015 15.16.36 CEST, "Zdeněk Průša" <notifications@github.com> wrote:
>A quick fix is to delete mex/block_interface.mex...
>The Matlab version is probably not much slower.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ltfat/ltfat/issues/44#issuecomment-146193448

-- 
Sent from my VIC 20 with K-9 Mail.

**Comment by susnak** [comment]
Hi Peter, do you still have access to Matlab 2015b? If yes, could you pull, recompile and try running it again? Thanks.

**Comment by psoenderg** [comment]
I will try it next week. 

On 16. okt. 2015 07.16.17 CEST, "Zdeněk Průša" <notifications@github.com> wrote:
>Hi Peter, do you still have access to Matlab 2015b? If yes, could you
>pull, recompile and try running it again? Thanks.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ltfat/ltfat/issues/44#issuecomment-148610109

-- 
Sent from my VIC 20 with K-9 Mail.
