### ISSUE TITLE
Install fail in  Mac OX Gnu Octave 4.0.3

### ISSUE THREAD

**Issue by rickyzhang82** [ltfat/ltfat#57]
Install on Mac OX Gnu Octave 4.0.3

pkg install ltfat -forge;

``` 
clang: warning: argument unused during compilation: '-L/Applications/Octave.app/Contents/Resources/usr/opt/suite-sparse/lib'
clang: warning: argument unused during compilation: '-L/Applications/Octave.app/Contents/Resources/usr/opt/metis/lib'
In file included from comp_cellcoef2tf.cc:8:
In file included from ./ltfat_oct_template_helper.h:4:
../src/include/ltfat.h:22:10: fatal error: 'fftw3.h' file not found
#include <fftw3.h>
         ^
In file included from comp_atrousfilterbank_td.cc:8:
In file included from ./ltfat_oct_template_helper.h:4:
../src/include/ltfat.h:22:10: fatal error: 'fftw3.h' file not found
#include <fftw3.h>
         ^
In file included from comp_chirpzt.cc:8:
In file included from ./ltfat_oct_template_helper.h:4:
../src/include/ltfat.h:22:10: fatal error: 'fftw3.h' file not found
#include <fftw3.h>
         ^
In file included from comp_col2diag.cc:8:
In file included from ./ltfat_oct_template_helper.h:4:
../src/include/ltfat.h:22:10: fatal error: 'fftw3.h' file not found
#include <fftw3.h>
         ^
1 error generated.
make[1]: *** [comp_cellcoef2tf.oct] Error 1
make[1]: *** Waiting for unfinished jobs....
1 error generated.
make[1]: *** [comp_col2diag.oct] Error 1
```

**Comment by susnak** [comment]
Hello,

here are two ways how to fix this:

1) Install (development version!) of fftw3. I do not know how to do that 
on Mac OS. Maybe try using brew or something similar.

2) Download the archive ltfat-2.1.2.tar.gz manually from:
https://sourceforge.net/projects/octave/files/Octave%20Forge%20Packages/Individual%20Package%20Releases/

In the archive edit line 41 in oct/Makefile_unix
from
MKOCTFILEFLAGS = -I../src/include -I../src/include/ltfat -DNDEBUG 
-L../lib -lltfat
to
MKOCTFILEFLAGS = -I../src/thirdparty -I../src/include 
-I../src/include/ltfat -DNDEBUG -L../lib -lltfat

save the archive and try to install using
pkg install ltfat-2.1.2.tar.gz

Please try the second option first and let me know if it works.
I will fix that in the next release.

Zdenek

**Comment by nperraud** [comment]
Le 1 août 2016 à 11:35, Zdeněk Průša <notifications@github.com<mailto:notifications@github.com>> a écrit :

1) Install (development version!) of fftw3. I do not know how to do that
on Mac OS. Maybe try using brew or something similar.

If you have home-brew, you can install this library with

brew install fftw

**Comment by rickyzhang82** [comment]
My binary version Octave does comes with fftw3 library. 

I modified makefile below:

```
MKOCTFILEFLAGS = -I../libltfat/thirdparty -L/Applications/Octave.app/Contents/Resources/usr/lib -I../libltfat/include -I../libltfat/include/ltfat -DNDEBUG -L../lib -lltfat
```

Then run 
```
ltfatstart
ltfatmex
```

It can compile without the issues. The original Makefile can't find the location of linked library or headers. 

But I still don't know how to install it in Octave. After modification and packaging that files. but it failed to run 

```
pkg install ltfat-2.1.2.tar.gz
```

Octave complained that it missed DESCRIPTION file. 

I used binary bundle Octave from the link https://sourceforge.net/projects/octave/files/Octave%20MacOSX%20Binary/2016-07-11-binary-octave-4.0.3/octave_gui_403_appleblas.dmg/download

I don't want to spend hours to build Octave in my Macports.

**Comment by susnak** [comment]
> My binary version Octave does comes with fftw3 library. 

Yes, but  fftw3.h is missing or it is not in the search path. Usually, the header files are part of the development version of the library. That is why I suggested to install the library separatelly.

ltfat comes with its own copy of fftw3.h, but the path is not set properly in the Makefile. 

 > But I still don't know how to install it in Octave. After modification and packaging that files. but it failed to run 

... with the same error message?

**Comment by rickyzhang82** [comment]
I did find fftw3 headers in Octave binary /Applications/Octave.app/Contents/Resources/usr/include.
But ltfat doesn't come with fftw3 library.

It is different message. It even didn't start to compile at all.  It states that package missing DESCRIPTION files.
```
>> pkg install ltfat-2.1.2.tar.gz;
package is missing file: DESCRIPTION
error: called from 'verify_directory' in file /Applications/Octave.app/Contents/Resources/usr/Cellar/octave/4.0.3/share/octave/4.0.3/m/pkg/private/verify_directory.m near line 30, column 7
```

**Comment by susnak** [comment]
I did not say that ltfat comes with fftw3 library, It comes just with the header file fftw3.h. It is in src/thirdparty, but that is beside the point now that we know you have your own.

If the DESCRIPTION fie is missing, you must have changed the archive structure or you are working with some different package.  Are you sure you have the one from
https://sourceforge.net/projects/octave/files/Octave%20Forge%20Packages/Individual%20Package%20Releases/

The packages you can download from ltfat homepage do not have the Octave forge package structure.

**Comment by rickyzhang82** [comment]
I got the package from github release tab. https://github.com/ltfat/ltfat/releases/download/2.1.2/ltfat-2.1.2.tgz

I'd suggest
* add this in INSTALL
* write a script to generate Octave forge package structure from your git repo.

**Comment by susnak** [comment]
Yes, that is not a Octave forge package. I specifically told you to get the one from Octave Forge. 
The package will however work in both Octave and Matlab.

We do not host ltfat Octave forge package and there are reasons for that.

There is a big note at
https://github.com/ltfat/ltfat/releases/
advising to install ltfat from Octave Forge if you are on Octave.

We have a script which converts the repository to a Octave forge package (among other things), but it is not intended to be used by end users. I don't see the point . You can always get the official ltfat octave forge package from
https://sourceforge.net/projects/octave/files/Octave%20Forge%20Packages/Individual%20Package%20Releases/

**Comment by rickyzhang82** [comment]
I knew. But it failed to compile as you know. There is nothing I can do except messing release build.

It would be great to include the conversion script in your git repo. It is nice to have. Thanks for your great work!

**Comment by susnak** [comment]
The octave forge package is just a tarball with source codes. Nothing more.
(See http://wiki.octave.org/wiki/images/2/29/OctConf-2015-Octave-packages.pdf)

If you insist, see the following blog post:
http://neilhopcroft.com/fixing-of-ltfat/

I still don't get why would you want to do it the hard way, but suit yourself.

Anyway, I am closing this.
