### ISSUE TITLE
reproduceable noise

### ISSUE THREAD

**Issue by fpga-1234** [ltfat/ltfat#61]
It would be nice to be able to specify a seed with noise to generate reproducible noise.
I also noticed that the flags passed to normalized do not appear as optional parameters in the online documentation.

**Comment by susnak** [comment]
Hello,
I assume you are talking about function [noise](http://ltfat.github.io/doc/signals/noise.html)
Adding an additional argument for specifying seed should not be a problem. In fact, you can specify the seed by calling randn('seed',n) or rng(n) before calling noise. Note that rng is not available on Octave and randn('seed',n) is deprecated on newer versions of Matlab.

The online documentation of noise specifically refers user to look for the normalization flags in the help of the function [normalize](http://ltfat.github.io/doc/sigproc/normalize.html):

> By default, the noise is normalized to have a unit energy, but this can be changed by passing a flag to normalize.

I admit that it is a bit confusing. It should instead say something like:

By default, the noise is normalized to have a unit energy, but this can be changed by passing any flag understood by normalize.

**Comment by fpga-1234** [comment]
Thanks for clearing up how to set the seed. 
My issue with the documentation of 'noise' and the 'normalize' flag is that is does not show up in the usage
