### ISSUE TITLE
doc error of UFWT(Undecimated Fast Wavelet Transform)

### ISSUE THREAD

**Issue by yangysc** [ltfat/ltfat#64]
In this page [https://ltfat.github.io/doc/wavelets/ufwt.html](url), given decomposition level  **J** and the length **L** of 1-D signal, should **the size of output c = ufwt(f, w, J) is L(J+1)**,  rather than (L * J + 1)  given in the page.

**Comment by susnak** [comment]
Yes, it should.
Thanks.

**Comment by yangysc** [comment]
May I bother to ask what's the difference between the **UFWT** in ltfat and **swt** in [matlab](https://cn.mathworks.com/help/wavelet/ref/swt.html) or [PyWavelets](https://pywavelets.readthedocs.io/en/latest/ref/swt-stationary-wavelet-transform.html).  I'm confused which  implement is right. It seems swt in matlab(or PyWavelets) requires the length of 1D signal needs to be 2^N, which is not required in UFWT. Could anyone tell me  more details of the implement of UFWT . Thanks in advance.

**Comment by susnak** [comment]
Conceptually there is no difference. The coefficients are however not compatible even if you use UFWT with signal length equal to a power of two.
As for which implementation is right, you will have to decide for yourself. I am strongly biased ;)

The implementation is done using the A-trous algorithm. It is very similar to the classical FWT, except no subsampling is involved and the filters are instead upsampled i.e. progressively more and more zeros are inserted between the filter samples as the level grows.

More details can be found in section 4 here http://ltfat.github.io/notes/ltfatnote038.pdf

**Comment by yangysc** [comment]
Thanks for your contribution. I'm still wondering if there is a **online**  version of undecimated wavelet transform , in order to handle **real time** data analysis. Because when using **wavelet transformed data** to **train** a machine learning model,  for the test data, they shoud do the same transformation similar to that in training stage. How to handle boundary when using wavelet transform is troublesome(_symmetry is not appropriate for real time data analysis_), and I think that the  transform of the test data should benefit from transform of training data, which is not the cases of the literature. So I'm confused how to transform test data. Thanks in advance.

**Comment by adityaapte** [comment]
Can you please provide guidance on obtaining (A,V,H,D) matrices from UFWT similar to Matlab's swt2? For example, [A,H,V,D] = swt2(img2D,1,'sym4');

**Comment by adityaapte** [comment]
Here is code snippet to get A,H,V,D components comparable to swt2. The coefficients don't match exactly, but visually similar.
```
img2D = cameraman;

[A,H,V,D] = swt2(img2D,1,'sym4');

[c,infoS] = ufwt(img2D,'sym4',1);
d = ufwt(squeeze(c(:,1,:))','sym4',1);
e = ufwt(squeeze(c(:,2,:))','sym4',1);

Altfat = squeeze(d(:,1,:))'*2;
Vltfat = squeeze(d(:,2,:))'*2;
Hltfat = squeeze(e(:,1,:))'*2;
Dltfat = squeeze(e(:,2,:))'*2;


figure,
subplot(1,2,1), imagesc(A)
title('Matlab - A'), colorbar
subplot(1,2,2), imagesc(Altfat)
title('LTFAT - A'), colorbar

figure, 
subplot(1,2,1), imagesc(H)
title('Matlab - H'), colorbar
subplot(1,2,2), imagesc(Hltfat)
title('LTFAT - H'), colorbar

figure,
subplot(1,2,1), imagesc(V)
title('Matlab - V'), colorbar
subplot(1,2,2), imagesc(Vltfat)
title('LTFAT - V'), colorbar

figure,
subplot(1,2,1), imagesc(D)
title('Matlab - D'), colorbar
subplot(1,2,2), imagesc(Dltfat)
title('LTFAT  -D'), colorbar

```
![image](https://user-images.githubusercontent.com/840839/216720680-4a950e89-ff10-4d0c-b51c-e2655131e7d1.png)
![image](https://user-images.githubusercontent.com/840839/216720726-eefb795e-0a0b-4b94-9612-d86fb76a12e6.png)
![image](https://user-images.githubusercontent.com/840839/216720768-f7774e27-9e6e-4ad0-8990-c2308624747b.png)
![image](https://user-images.githubusercontent.com/840839/216720815-071ecfb6-4afb-4a4d-a952-966b92b326f7.png)

**Comment by allthatsounds** [comment]
Thanks! If you'd like to carry this further, you could additionally match the coefficients (up to ~10e-10 range) by accounting for the differences in periodic boundary extension as below:

```
img2D = cameraman;

[A,H,V,D] = swt2(img2D,1,'sym4');

[c,infoS] = ufwt(img2D,'sym4',1);
d = ufwt(squeeze(c(:,1,:))','sym4',1);
e = ufwt(squeeze(c(:,2,:))','sym4',1);

Altfat = squeeze(d(:,1,:))'*2;
Vltfat = squeeze(d(:,2,:))'*2;
Hltfat = squeeze(e(:,1,:))'*2;
Dltfat = squeeze(e(:,2,:))'*2;

%shift from end towards beginning of array
A = circshift(A,1);
A = circshift(A,1,2);

norm(Altfat-A)
```

**Comment by adityaapte** [comment]
Thanks, the following matches all the components.

```
img2D = cameraman;

[A,H,V,D] = swt2(img2D,1,'sym4');

[c,infoS] = ufwt(img2D,'sym4',1);
e = ufwt(squeeze(c(:,2,:))','sym4',1);
d = ufwt(squeeze(c(:,1,:))','sym4',1);

Altfat = squeeze(d(:,1,:))'*2;
Vltfat = squeeze(d(:,2,:))'*2;
Hltfat = squeeze(e(:,1,:))'*2;
Dltfat = squeeze(e(:,2,:))'*2;

Altfat = circshift(Altfat,-1,1);
Altfat = circshift(Altfat,-1,2);
norm(Altfat-A)

Vltfat = circshift(Vltfat,-1,1);
Vltfat = circshift(Vltfat,1,2);
norm(Vltfat-V)

Dltfat = circshift(Dltfat,1,1);
Dltfat = circshift(Dltfat,1,2);
norm(Dltfat-D)

Hltfat = circshift(Hltfat,1,1);
Hltfat = circshift(Hltfat,-1,2);
norm(Hltfat-H)

```

**Comment by adityaapte** [comment]
Here is equivalent of swt for 1d input.
```
x = rand(104,1);
J = 1;
w = 'sym4';
len = length(x);
swc = zeros(len,J+1);

swcTmpM = sqrt(2)*flip(ufwt(x,w,J),2);
for i=1:J+1
    swc(:,i) = circshift(swcTmpM(:,i),(-1)^(i+1));
end
swc = swc'; % for Matlab compatibility

```

**Comment by adityaapte** [comment]
The above routines work well for J=1. How can this be extended for J>1?

**Comment by allthatsounds** [comment]
Essentially, you need to account for the iterative application of the periodic extension and of conv2, I suppose you want something along the lines of
```
    Altfat = circshift(Altfat,-2^(J)+1,1);
    Altfat = circshift(Altfat,-2^(J)+1,2);%account for iterative extension
    norm(Altfat-A(:,:,J)./2^(J-1)) %account for iterative conv2
```
However, clearly, this gets less and less accurate with increasing J. Ultimately, these are just two different algorithms, so do handle with care.

**Comment by aditiiyer** [comment]
Hi, I noticed the coefficients returned by ufwt.m (ltfat release [v2.5.0](https://github.com/ltfat/ltfat/releases/download/v2.5.0/ltfat-2.5.0-win64.zip)) are different when called from Matlab vs. Octave. Is there a recommended release for Octave that would return compatible values? E.g. below:
![ufwt_example](https://user-images.githubusercontent.com/14824313/217942780-a7f2ceba-38d6-463b-bcb4-f27bb0edf06c.jpg)

**Comment by adityaapte** [comment]
> Essentially, you need to account for the iterative application of the periodic extension and of conv2, I suppose you want something along the lines of
> 
> ```
>     Altfat = circshift(Altfat,-2^(J)+1,1);
>     Altfat = circshift(Altfat,-2^(J)+1,2);%account for iterative extension
>     norm(Altfat-A(:,:,J)./2^(J-1)) %account for iterative conv2
> ```
> 
> However, these are still two different algorithms, so do handle with care.

I opened a new issue https://github.com/ltfat/ltfat/issues/145 as the discussion seem to deviate from the original question raised in this issue. Greatly appreciate your help.

**Comment by allthatsounds** [comment]
> Hi, I noticed the coefficients returned by ufwt.m (ltfat release [v2.5.0](https://github.com/ltfat/ltfat/releases/download/v2.5.0/ltfat-2.5.0-win64.zip)) are different when called from Matlab vs. Octave. Is there a recommended release for Octave that would return compatible values? Including a snippet of sample coefficients from Matlab & Octave below: ![ufwt_example](https://user-images.githubusercontent.com/14824313/217942780-a7f2ceba-38d6-463b-bcb4-f27bb0edf06c.jpg)

Sorry, I could not reproduce your Octave results, neither with nor without the C backend, neither on Windows nor under Linux.
