### ISSUE TITLE
Remove the compiled mex/ltfatarghelper.mexw64 from the release package...

### ISSUE THREAD

**Issue by petibub** [ltfat/ltfat#66]
... because it crashes ltfatarghelper (on Windows 10, Matlab2013 and 2016)

So the current procedure for a first-time user of LTFAT is: 
1) download the package. Don't start the LTFAT!
2) delete manually ltfatarghelper mex/ltfatarghelper.mexw64. 
3) start the LTFAT by calling ltfatstart

If you don't delete the file (Step 2), ltfatarghelper crashes. 

If the LTFAT is started before deleting (skipping step 2), Matlab loads the mexw64 file and it cannot be deleted anymore from Matlab. Matlab must be restarted. 

Of course there is the option of compilation (ltfatmex), but then a compiler must be installed and the road to use the LTFAT is even longer and more complicated.

**Comment by susnak** [comment]
The downloadable packages ltfat-2.2.0-win32.zip and ltfat-2.2.0-win64.zip now don't include mex/ltfatarghelper.mexw64

**Comment by petibub** [comment]
Thanks a lot!
