### ISSUE TITLE
franabp fails with default options

### ISSUE THREAD

**Issue by kakila** [ltfat/ltfat#68]
Hi,

The function franabp (tested Octave-Forge) fails with the default option of starting with zero vectors. The line that fails is 275

`relres = norm(c(:)-tc0(:))/norm(tc0(:));`

because tc0 is all zeros. Since this is just an initialization I guess either starting tc0 as ones or rand instead of zeros should solve the problem.

**Comment by susnak** [comment]
Hi,
thanks. Although it does not make sense to use the function to approximate zero vectors, it should definitely not throw an error.
