### ISSUE TITLE
sgram - errors with 'mesh' and 'fmax' options

### ISSUE THREAD

**Issue by peterlongfield** [ltfat/ltfat#72]
Dear team,

Installed ltfat with octave 4.0.0 on LInuxMint 18.2 Sonya
.
I got the following errors.  (the same vector y is plotted nicely with no option, or with the 'surf' or 'contour' option)

>> sgram(y,250,'fmax',20)
error: too many input arguments
error: called from
    ifftreal at line 39 column 1
    fftresample at line 57 column 4
    sgram at line 175 column 4
>> sgram(y,250,'mesh')
error: SGRAM: Unknown parameter: mesh
error: called from
    ltfatarghelper at line 274 column 7
    sgram at line 165 column 13
 ltfathelp

--- LTFAT - The Linear Time Frequency Analysis toolbox. ---

Version 2.1.1

Installed modules:

Name:            Version:  Description
 auditory          2.1.1   LTFAT - Simple auditory processing
 blockproc         2.1.1   LTFAT - Block processing
 demos             2.1.1   LTFAT - Demos
 deprecated        2.1.1   LTFAT - Deprecated functions
 filterbank        2.1.1   LTFAT - Filterbanks
 fourier           2.1.1   LTFAT - Basic Fourier and DCT analysis.
 frames            2.1.1   LTFAT - Frames
 gabor             2.1.1   LTFAT - Gabor analysis
 nonstatgab        2.1.1   LTFAT - Non-stationary Gabor systems
 operators         2.1.1   LTFAT - Operators
 quadratic         2.1.1   LTFAT - Quadratic time-frequency distributions
 signals           2.1.1   LTFAT - Signals
 sigproc           2.1.1   LTFAT - Signal processing tools
 wavelets          2.1.1   LTFAT - Wavelets
Type "help modulename" where "modulename" is the name of one
of the modules to see help on that module.

For other questions, please don't hesitate to send an email to ltfat-help@lists.sourceforge.net.
>>

**Comment by susnak** [comment]
Hi, 
thanks for reporting this.
The 'mesh' option was removed for some reason (it is never handled in the code), but the help was not updated.  
The 'fmax' parameter works on my Octave 4.2.1 with ltfat 2.2.1, so please just update to the newer version of ltfat.  `pkg install ltfat -forge` should do the trick. 
Zdenek
