### ISSUE TITLE
Addition of pseudo-differential operators.

### ISSUE THREAD

**Issue by jvnv** [ltfat/ltfat#8]
The pseudo-differential operators that should at least be added to LTFAT are the following:
- The Weyl correspondence.
- The Kohn-Nirenberg correspondence.

These pseudo-differential operators should be integrated into the "operator framework" of LTFAT. Further should the pseudo-differential operators satisfy the common relations with the quadratic time-frequency distributions.

**Comment by psoenderg** [comment]
Which  pseudo-differential operators do you plan to add?
