### ISSUE TITLE
cqtfilters and audfilters documentation

### ISSUE THREAD

**Issue by nholighaus** [ltfat/ltfat#82]
In the documentation of cqtfilters, the description of the optional 'Qvar' parameter states

If the value is **less than one**, thesystem may no longer be painless.

Should it not be **larger than one**?

In audfilters, the description of the 'warped' parameter should read

Create asymmetric filters that are **symmetric** on the auditory scale.

**Comment by susnak** [comment]
cqtfilters: Q should be inversely proportional to the bandwidth Q=fc/bw i.e. decreasing Q increases bandwidth. It is however used the other way around in the code.
