### ISSUE TITLE
Introduce tutorials as Jupyter notebooks

### ISSUE THREAD

**Issue by susnak** [ltfat/ltfat#91]
... using  [octave_kernel](https://github.com/Calysto/octave_kernel) and [matlab_kernel](https://github.com/Calysto/matlab_kernel)

**Comment by psoenderg** [comment]
Great idea! We are using Jupyter extensively to generate documentation for our machine learning system.

We use http://papermill.readthedocs.io/en/latest/ to parameterize notebooks, and nbconvert to convert the output to different formats.

**Comment by nperraud** [comment]
I agree, I think it is an excellent idea.

**Comment by susnak** [comment]
I ended up creating a separate repository, because the notebooks an easilly have several MB
https://github.com/ltfat/notebooks
There are already two tutorials, feel free to check them out.

**Comment by susnak** [comment]
I also want to make them easily readable online. Github has a notebook reader integrated.
Or does it make more sense to export them as a static webpage?

**Comment by psoenderg** [comment]
I think your approach makes the most sense. Ours is different, we don't have github, and we run each report many times on different data, so we go by the static HTML pages. 
-- 
Dette er sendt fra min mobiltelefon. Undskyld at jeg fatter mig i korthed.
