### ISSUE TITLE
I'm unclear how to get ltfat + phaseret working with octave.

### ISSUE THREAD

**Issue by derifatives** [ltfat/ltfat#92]
On a modern linux box, following the instructions at https://github.com/ltfat/ltfat/releases/tag/2.3.1, I typed:
pkg install ltfat -forge

There were some warnings:
   pkg install ltfat -forge

configure: WARNING: Portaudio lib not found. Disabling support of the block processing framework.
ar: creating build/libltfat.a
warning: doc_cache_create: unusable help text found in file 'playrec'
warning: doc_cache_create: unusable help text found in file 'polyboolmex'
For information about changes from previous versions of the ltfat package, run 'news ltfat'.

Not sure if any of those are important. It looks like it installed into '~/octave/ltfat-2.3.1/'. So far so good.

I downloaded phaseret (from https://github.com/ltfat/phaseret/releases/tag/v0.2.1), unzipped the .tgz, went to the directory, hit phaseretstart, and got:

error: PHASERETSTART: LTFAT not found. Please install LTFAT 2.1.3 or newer.
error: called from
    phaseretstart at line 51 column 5

This was a little confusing to me, since 'news ltfat' did work, and seems to indicate that ltfat is installed. Looking it over, it seems maybe I have to manually addpath the path to ltfat? If I do that, ltfatstart works, although it always says 'Error with backend, consider running "ltfatmex clean" immediately', even if I run ltfatmex clean and then run ltfatstart again.

Additionally, even with this path added, I still get the same error with phaseretstart. 

Any help is welcome. If the help is "octave isn't actually going to work," better to know that now than after I sink a lot more time in. (I can get matlab on this computer if necessary, but it's a hassle.)

**Comment by derifatives** [comment]
Preliminarily, it seems that manually adding *both* 
~/octave/ltfat-2.3.1/
~/octave/ltfat-2.3.1/x86_64-pc-linux-gnu-api-v51

seems to allow me to run both ltfatstart and phaseretstart without error.

**Comment by susnak** [comment]
pkg install only installs the toolbox.
You also need to run
pkg load ltfat
(it just runs ltfatstart).

**Comment by susnak** [comment]
(I updated the instructions at https://github.com/ltfat/ltfat/releases/tag/2.3.1)
