### ISSUE TITLE
Compiling libltfat for MATLAB on OSX fails

### ISSUE THREAD

**Issue by ianesten** [ltfat/ltfat#93]
cd ltfat/inst
ltfaxmex

========= Compiling libltfat ==============
Error using cd
Cannot CD to /Users/ieste/Documents/MATLAB/3p/ltfat/inst/lib/ltfatcompat (Name is nonexistent or not a directory).

Changing line 233 to:
cd([bp, '..',filesep,'lib',filesep,'ltfatcompat']);
gives this error:

========= Compiling libltfat ==============
Error using ltfatmex (line 252)
Failed to build LTFAT libs:
 make -C ../../libltfat build/libltfat.a OPTCFLAGS=-DLTFAT_LARGEARRAYS
make: *** ../../libltfat: No such file or directory.  Stop.
make: *** [all] Error 2

ltfat/src/modules/libltfat seems like it should be the directory passed to make, but does not contain a makefile.

**Comment by susnak** [comment]
Hi, you are probably just using the wrong release package. Try this one:
https://github.com/ltfat/ltfat/releases/download/2.3.1/ltfat-2.3.1-src.tgz

**Comment by ianesten** [comment]
That was it. Thanks!
